/* mipslabwork.c
   Written by johvh & davidjo2.
*/

#include <stdint.h>
#include <pic32mx.h>
#include "gameHeader.h"
#include <stdlib.h>

#define PROCESSOR_SPEED 800000

int timeoutcount = 0;
int lastNumber = 0; // last number generated by getRandomInt

/* Interrupt Service Routine */
void user_isr( void ) {
    if (timeoutcount>9 && (IFS(0) & 0x100)>>8) {
        PORTE += 1;
        timeoutcount = 0;
    }
    IFS(0) &= 0xFFFFFEFF;
    timeoutcount++;
}

/*
* Generate random integer depending
* on how many switches are activated
* @param switchAmount
* @return random int
*/
/*
int getRandomInt(int switchAmount){
    int random = lastNumber;
    while(lastNumber == random){
        switch(switchAmount){
            case 2:
                random = rand() % 4;
                break;
            case 3:
                random = rand() % 5 + 3;
                break;
            case 4:
                random = rand() % 11 + 5;
                break;
        }
    }
    lastNumber = random;
    return random;
}
*/

/**
 * Convert binary to hex number.
 * @param binary number
 * @return hex number
 */
int hexConverter(int binary){
    int hex = 0x0;
    int i;
    for (i = 0; i < 4; i++) {
        int tempMod = binary % 2;
        if(tempMod){
            hex += 0xf;
            hex <<= 4;
        } else {
            hex <<= 4;
        }
        binary >>= 1;
    }
    return hex;
}

int accumulator = 0;
/**
 * Update game, this is the game loop.
 */
void updateRunning(FPS) {
    accumulator++;
    if(accumulator % (PROCESSOR_SPEED/FPS) == 0) {
        display_update();
    }
}
